version: '3.8'
services:

  db-strapi:
    image: '${PROJECT_NAME}/${IMAGE_PREFIX}-db-strapi:${SAMPLEPROJECT_TAG:-latest}'
    container_name: '${IMAGE_PREFIX}-db-strapi'
    restart: always
    volumes:
      - db-strapi:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${STRAPI_DB_NAME}
      - POSTGRES_PASSWORD=${STRAPI_DB_PW}
      - POSTGRES_SCHEMA=${STRAPI_DB_SCHEMA}
      - POSTGRES_USER=${STRAPI_DB_USER}

  strapi-backend:
    image: '${PROJECT_NAME}/${IMAGE_PREFIX}-strapi:${SAMPLEPROJECT_TAG:-latest}'
    container_name: '${IMAGE_PREFIX}-strapi-backend'
    restart: always
    environment:
      - ADMIN_JWT_SECRET=${STRAPI_ADMIN_JWT_SECRET}
      - API_TOKEN_SALT=${STRAPI_API_TOKEN_SALT}
      - APP_KEYS=${STRAPI_APP_KEYS}
      - DATABASE_CLIENT=${STRAPI_DB_CLIENT}
      - DATABASE_HOST=${STRAPI_DB_HOST}
      - DATABASE_NAME=${STRAPI_DB_NAME}
      - DATABASE_PASSWORD=${STRAPI_DB_PW}
      - DATABASE_PORT=${STRAPI_DB_PORT}
      - DATABASE_SCHEMA=${STRAPI_DB_SCHEMA}
      - DATABASE_USERNAME=${STRAPI_DB_USER}
      - JWT_SECRET=${STRAPI_JWT_SECRET}
      - NODE_ENV=${STRAPI_NODE_ENV}
      - S3_ACCESS_KEY
      - S3_SECRET
      - S3_BUCKET
      - S3_REGION
    ports:
      - 1337:1337
    depends_on:
      - "db-strapi"

  db-nextjs:
    image: '${PROJECT_NAME}/${IMAGE_PREFIX}-db-nextjs:${SAMPLEPROJECT_TAG:-latest}'
    container_name: '${IMAGE_PREFIX}-db-nextjs'
    restart: always
    volumes:
      - db-nextjs:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NEXTJS_DB_NAME}
      - POSTGRES_PASSWORD=${NEXTJS_DB_PW}
      - POSTGRES_SCHEMA=${NEXTJS_DB_SCHEMA}
      - POSTGRES_USER=${NEXTJS_DB_USER}

  nextjs-app:
    image: '${PROJECT_NAME}/${IMAGE_PREFIX}-nextjs-app:${SAMPLEPROJECT_TAG:-latest}'
    container_name: '${IMAGE_PREFIX}-nextjs-app'
    environment:
      - STRAPI_API_TOKEN
      - STRAPI_BACKEND_URL
      - NEXTJS_DB_URL
      - SECRET_COOKIE_PASSWORD
      - NEXT_TELEMETRY_DISABLED=1
      - S3_ACCESS_KEY
      - S3_SECRET
      - S3_BUCKET
      - S3_REGION
    restart: always
    depends_on:
      - "db-nextjs"

  nginx:
    image: '${PROJECT_NAME}/${IMAGE_PREFIX}-nginx:${SAMPLEPROJECT_TAG:-latest}'
    container_name: '${IMAGE_PREFIX}-nginx'
    environment:
      - NGINX_SERVER_NAME
      - NGINX_STRAPI_SERVER_NAME=${STRAPI_BACKEND_HOST}
      - RESOLVER
      - ENVIRONMENT
      - NGINX_CERTIFICATE_NAME
      - NEXTJS_HOST
      - STRAPI_HOST
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - "nextjs-app"
      - "strapi-backend"
    volumes:
      - certbot_certificates:/etc/letsencrypt
      - certbot_challenges:/usr/share/nginx/html/.well-known/acme-challenge

volumes:
  db-strapi:
  db-nextjs:
  certbot_certificates:
  certbot_challenges:
